"""empty message

Revision ID: 22bc6fc2d1ec
Revises: 2d65c1bfa993
Create Date: 2021-06-04 14:13:12.150276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22bc6fc2d1ec'
down_revision = '2d65c1bfa993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'summary')
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###
