"""empty message

Revision ID: 5b2c77059914
Revises: 22bc6fc2d1ec
Create Date: 2021-06-04 18:35:12.098264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b2c77059914'
down_revision = '22bc6fc2d1ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('imageOne', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('imageThree', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('imageTwo', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('image_url_main', sa.String(length=255), nullable=True))
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('products', 'image_url_main')
    op.drop_column('products', 'imageTwo')
    op.drop_column('products', 'imageThree')
    op.drop_column('products', 'imageOne')
    # ### end Alembic commands ###
